source 'https://github.com/CocoaPods/Specs.git'

target 'ZRScrollableTabBar', :exclusive => true do
  pod "ZRScrollableTabBar", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ZRScrollableTabBar", :path => "../"

  
end
